### ISSUE TITLE
Add ability to specify initial multi-column sort using ts-default?

### ISSUE THREAD

**Issue by pursual** [mattiash/angular-tablesort#19]
Is there a method for specifying a default sort that spans multiple columns?

**Comment by mattiash** [comment]
You can set ts-default on several columns.

**Comment by pursual** [comment]
Is there anyway to control the order of the multiple ts-defaults?

**Comment by mattiash** [comment]
No, you cannot do that. It sorts by the first ts-default and then the second and so on. In practice, I have never needed to control that. I think that if you have a column with several rows that you want to sort by, then it makes sense to sort by the leftmost column first. This means that the table will look like this

column 1 | column 2
------------|--------------
A | 1
A | 2
A | 3
B | 1
B | 2

instead of this

column 2 | column 1
------------|--------------
1 | A
2 | A
3 | A
1 | B
2 | B

In the first table, it is easy to see that the table has been sorted by column 1 first and then column 2. In the second table that is not as obvious.
